=== brutoslabs/brutos-annotation/trunk/brutos-core/src/main/resources/brutos-controllers-1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Brutos Web MVC http://www.brutosframework.com.br/
  Copyright (C) 2009 Afonso Brandao. (afonso.rbn@gmail.com)
 
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
 
         http://www.apache.org/licenses/LICENSE-2.0
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.brutosframework.com.br/schema/controllers"
            xmlns="http://www.brutosframework.com.br/schema/controllers"
           elementFormDefault="qualified">

        <xsd:element name="controllers">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:any namespace="##other" processContents="strict"
                            minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="import" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                          <xsd:attribute name="resource" type="xsd:string"/>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="interceptors" type="interceptors"
                            minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="controller" type="controller"
                            minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
  <!-- *************************************************************** -->

    <xsd:complexType name="controller">
        <xsd:sequence>
            <xsd:element name="alias" minOccurs="0" type="alias" maxOccurs="unbounded"/>
            <xsd:element name="interceptor-ref" type="interceptor-ref" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="property" type="controller-property" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="action" type="action" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="throw-safe" minOccurs="0" type="throw-safe" maxOccurs="unbounded"/>
        </xsd:sequence>

        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="dispatcher" type="dispatcher" default="forward"/>
        <xsd:attribute name="view" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="class" type="xsd:string"/>
        <xsd:attribute name="action-id" type="xsd:string" default="invoke"/>
        <xsd:attribute name="action-type" type="actionType"/>
        <xsd:attribute name="default-action" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="action">
        <xsd:sequence>
            <xsd:element name="parameter" minOccurs="0"
                     type="parameter" maxOccurs="unbounded"/>
            <xsd:element name="throw-safe" minOccurs="0"
                     type="throw-safe" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="executor" type="xsd:string"/>
        <xsd:attribute name="result" type="xsd:string"/>
        <xsd:attribute name="result-rendered" type="xsd:boolean" default="false"/>
        <xsd:attribute name="view" type="xsd:string"/>
        <xsd:attribute name="dispatcher" type="dispatcher" default="forward"/>
    </xsd:complexType>

    <xsd:complexType name="throw-safe">
        <xsd:attribute name="view" type="xsd:string"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="dispatcher" type="dispatcher" default="forward"/>
    </xsd:complexType>

    <xsd:complexType name="mapping-bean">
        <xsd:sequence>
            <xsd:element name="constructor-arg" type="constructor-arg" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="key" type="key-collection" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="element" type="element-collection" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="separator" type="xsd:string" default="."/>
        <xsd:attribute name="index-format" type="xsd:string" default="[$index]"/>
        <xsd:attribute name="factory" type="xsd:string"/>
        <xsd:attribute name="method-factory" type="xsd:string"/>
        <xsd:attribute name="target" type="class" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="mapping-ref">
        <xsd:sequence>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="bean" type="xsd:string"/>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="mapping" type="xsd:boolean" default="false"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="class">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="((\[)+([Z|B|C|D|F|I|J|S]){0,1})|(((\[)+L)([a-z]|[A-Z])+(\.([a-z]|[A-Z]|[0-9])+)*\;)|(([a-z]|[A-Z])+(\.([a-z]|[A-Z]|[0-9])+)*)"/>
        <!--<xsd:pattern value="([a-z]|[A-Z])+(\.([a-z]|[A-Z]|[0-9])+)*"/>-->
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="uri">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="(\/([a-z]|[A-Z]|[0-9])+)*"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="scope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="request"/>
            <xsd:enumeration value="session"/>
            <xsd:enumeration value="application"/>
            <xsd:enumeration value="prototype"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="actionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="parameter"/>
            <xsd:enumeration value="hierarchy"/>
            <xsd:enumeration value="detached"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->
  
    <xsd:simpleType name="dispatcher">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="include"/>
            <xsd:enumeration value="forward"/>
            <xsd:enumeration value="redirect"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="controllerscope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="request"/>
            <xsd:enumeration value="session"/>
            <xsd:enumeration value="application"/>
            <xsd:enumeration value="flash"/>
            <xsd:enumeration value="ioc"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:simpleType name="enum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ordinal"/>
            <xsd:enumeration value="string"/>
        </xsd:restriction>
    </xsd:simpleType>

  <!-- *************************************************************** -->

    <xsd:complexType name="property">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="null" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
        <xsd:attribute name="bean" type="xsd:string"/>
        <xsd:attribute name="mapping" type="xsd:boolean" default="false"/>
    </xsd:complexType>

  <!-- *************************************************************** -->
  
    <xsd:complexType name="constructor-arg">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="null" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <!--<xsd:attribute name="name" type="xsd:string"/>-->
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="bean" type="xsd:string"/>
        <xsd:attribute name="mapping" type="xsd:boolean" default="false"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <!--<xsd:attribute name="mapping-name" type="xsd:string"/>-->
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="key-collection">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="null" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="bean" type="xsd:string" default="key"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="element-collection">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="null" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="bean" type="xsd:string" default="element"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="validator">
        <xsd:sequence>
            <xsd:element name="rule" type="rule"  minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="message" type="xsd:string" use="required"/>
    </xsd:complexType>
  <!-- *************************************************************** -->

    <xsd:complexType name="rule">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="value" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
  <!-- *************************************************************** -->

    <xsd:complexType name="controller-property">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="property-name" type="xsd:string" use="required"/>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="bean" type="xsd:string"/>
        <xsd:attribute name="mapping" type="xsd:boolean"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="xsd:string"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="parameter">
        <xsd:choice>
            <xsd:element name="ref" type="mapping-ref" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="bean" type="mapping-bean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator" type="validator" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="null" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="bean" type="xsd:string"/>
        <xsd:attribute name="mapping" type="xsd:boolean"/>
        <xsd:attribute name="scope" type="xsd:string" default="param"/>
        <xsd:attribute name="factory" type="class"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <!--
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
        <xsd:attribute name="enum-property" type="enum" default="ordinal"/>
        <xsd:attribute name="temporal-property" type="xsd:string" default="dd/MM/yyyy"/>
        <xsd:attribute name="ref" type="xsd:string"/>
        <xsd:attribute name="scope" type="xsd:string" default="request"/>
        <xsd:attribute name="factory" type="xsd:string"/>-->
    </xsd:complexType>

    <xsd:complexType name="props">
        <xsd:sequence>
            <xsd:element name="prop" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="value" type="xsd:string" minOccurs="0"/>
                    </xsd:sequence>
                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ref">
        <xsd:attribute name="bean" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="interceptors">
        <xsd:sequence>
            <xsd:element name="interceptor" type="interceptor" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="interceptor-stack" type="interceptor-stack" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="interceptor">
        <xsd:sequence>
            <xsd:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="class" type="xsd:string"/>
        <xsd:attribute name="default" type="xsd:boolean"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="param">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="value" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="alias">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"/>
        </xsd:simpleContent>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="interceptor-ref">
        <xsd:sequence>
            <xsd:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>

  <!-- *************************************************************** -->

    <xsd:complexType name="interceptor-stack">
        <xsd:sequence>
            <xsd:element name="interceptor-ref" type="interceptor-ref" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="default" type="xsd:boolean"/>
    </xsd:complexType>

</xsd:schema>

=== brutoslabs/brutos-annotation/trunk/brutos-web/src/test/resources/org/brandao/brutos/xml/helper/bean/bean-test-collection3.xml
<?xml version="1.0" encoding="UTF-8"?>

<controllers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.brutosframework.com.br/schema/controllers'
   xsi:schemaLocation='http://www.brutosframework.com.br/schema/controllers http://www.brutosframework.com.br/schema/controllers/brutos-controllers-1.1.xsd'>

    <controller
        class="org.brandao.brutos.helper.controller.SimpleController">

        <bean name="bean"
            target="java.util.LinkedList">
                <element>
                <bean factory="factory"
                    method-factory="getInstance"
                    target="org.brandao.brutos.helper.controller.SimpleBean">
                        <constructor-arg type="java.lang.String">
                            <ref bean="arg"/>
                        </constructor-arg>
                </bean>
                </element>
        </bean>

        <bean name="factory"
            target="org.brandao.brutos.helper.controller.FactoryBean"/>

    </controller>

</controllers>

=== brutoslabs/brutos-annotation/trunk/examples/webchat-xml/src/main/webapp/WEB-INF/brutos-config.xml
<?xml version="1.0" encoding="windows-1252"?>
<controllers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
              xmlns='http://www.brutosframework.com.br/schema/controllers'
              xmlns:context='http://www.brutosframework.com.br/schema/context'
              xsi:schemaLocation='
   http://www.brutosframework.com.br/schema/controllers http://www.brutosframework.com.br/schema/controllers/brutos-controllers-1.1.xsd
   http://www.brutosframework.com.br/schema/context http://www.brutosframework.com.br/schema/context/brutos-context-1.1.xsd'>

    <context:types>
        <context:type factory="org.brandao.webchat.controller.type.RoomServiceTypeFactory"/>
        <context:type factory="org.brandao.webchat.controller.type.SerializableObjectTypeFactory"/>
    </context:types>
    
    <interceptors>
        <interceptor name="checkUserInterceptor"
                     class="org.brandao.webchat.controller.interceptor.CheckUserInterceptor"/>
    </interceptors>
    
    <controller id="/Room/{roomID:\d+}" view="/layout/login.jsp" class="org.brandao.webchat.controller.RoomController">
        <interceptor-ref name="checkUserInterceptor"/>
        <property property-name="roomService" bean="roomID"/>
        <property property-name="currentUser" bean="sessionUser" scope="session"/>
        <action id="/login" view="/layout/login.jsp"/>
        <action id="/messagePart" view="/layout/messages.jsp"/>
        <action id="/sendPart" view="/layout/send.jsp"/>
        <action id="/send" executor="sendMessage">
            <parameter>
                <bean target="org.brandao.webchat.controller.entity.MessageDTO">
                    <property name="origin">
                        <bean target="org.brandao.webchat.controller.entity.UserDTO">
                            <property name="nick" bean="nick">
                                <validator message="userError">
                                    <rule name="maxlength" value="30"/>
                                    <rule name="matches" value="[^\&lt;\&gt;\s]*"/>
                                </validator>
                            </property>
                        </bean>
                    </property>
                    <property name="dest">
                        <bean target="org.brandao.webchat.controller.entity.UserDTO">
                            <property name="nick" bean="nick">
                                <validator message="userError">
                                    <rule name="maxlength" value="30"/>
                                    <rule name="matches" value="[^\&lt;\&gt;\s]*"/>
                                </validator>
                            </property>
                        </bean>
                    </property>
                    <property name="message" bean="message">
                        <validator message="msgError">
                            <rule name="maxlength" value="200"/>
                            <rule name="matches" value="[^\&lt;\&gt;]*"/>
                        </validator>
                    </property>
                </bean>
            </parameter>
        </action>
        <action id="/enter" executor="putUser" view="/layout/room.jsp">
            <parameter>
                <bean target="org.brandao.webchat.controller.entity.UserDTO">
                    <property name="nick" bean="nick">
                        <validator message="msgError">
                            <rule name="minlength" value="3"/>
                            <rule name="maxlength" value="30"/>
                            <rule name="matches" value="[^\&lt;\&gt;\s]*"/>
                        </validator>
                    </property>
                </bean>
            </parameter>
            <throw-safe view="/layout/login.jsp" name="exception" 
                        target="org.brandao.brutos.validator.ValidatorException"/>
            <throw-safe view="/layout/login.jsp" name="exception" 
                        target="org.brandao.webchat.model.UserExistException"/>
            <throw-safe view="/layout/login.jsp" name="exception" 
                        target="org.brandao.webchat.model.MaxUsersException"/>
            <throw-safe view="/layout/login.jsp" name="exception" 
                        target="java.lang.NullPointerException"/>
        </action>
        <action id="/exit" executor="removeUser">
            <parameter bean="user" scope="session"/>
        </action>
        <action id="/message" executor="getMessage" result-rendered="true"/>
        <action id="/listUsers" executor="getUsers" result-rendered="true"/>
    </controller>
</controllers>

=== brutoslabs/brutos-annotation/trunk/examples/Brutos-Interceptor/src/main/webapp/WEB-INF/brutos-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Brutos Web MVC http://www.brutosframework.com.br/
  Copyright (C) 2009 Afonso Brandão. (afonso.rbn@gmail.com)
-->

<controllers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
              xmlns='http://www.brutosframework.com.br/schema/controllers'
              xmlns:context='http://www.brutosframework.com.br/schema/context'
              xsi:schemaLocation='
   http://www.brutosframework.com.br/schema/controllers http://www.brutosframework.com.br/schema/controllers/brutos-controllers-1.1.xsd
   http://www.brutosframework.com.br/schema/context http://www.brutosframework.com.br/schema/context/brutos-context-1.1.xsd'>


    <interceptors>
        <interceptor name="testInterceptor"
                    class="br.brandao.interceptors.TestInterceptor"/>
    </interceptors>

    <controller id="/index.jbrs" view="/WEB-INF/jsp/index.jsp"
               class="br.brandao.controller.IndexController" action-type="parameter">
       <!-- todos os métodos são interceptados exceto o método4() -->
        <interceptor-ref name="testInterceptor">
            <param name="excludeMethods">method4</param>
        </interceptor-ref>

        <action id="method1" executor="method1"/>
        <action id="method2" executor="method2"/>
        <action id="method3" executor="method3"/>
        <action id="method4" executor="method4"/>

    </controller>

</controllers>

=== brutoslabs/brutos-annotation/trunk/brutos-web/src/test/resources/org/brandao/brutos/xml/helper/bean/bean-test-collection10.xml
<?xml version="1.0" encoding="UTF-8"?>

<controllers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.brutosframework.com.br/schema/controllers'
   xsi:schemaLocation='http://www.brutosframework.com.br/schema/controllers http://www.brutosframework.com.br/schema/controllers/brutos-controllers-1.1.xsd'>

    <controller
        class="org.brandao.brutos.helper.controller.SimpleController">

        <bean name="bean"
            target="java.util.LinkedList">
                <element>
                <bean
                    index-format="($index)"
                    target="org.brandao.brutos.helper.controller.SimpleBean">
                    <constructor-arg bean="str" type="java.lang.String">
                        <validator message="str is required">
                            <rule name="required"/>
                        </validator>
                    </constructor-arg>
                    <constructor-arg bean="arg" type="int">
                        <validator message="id is required">
                            <rule name="required"/>
                        </validator>
                    </constructor-arg>
                </bean>
                </element>
        </bean>

    </controller>

</controllers>

=== brutoslabs/brutos-annotation/trunk/brutos-web/src/test/resources/org/brandao/brutos/xml/helper/bean/bean-test-property14.xml
<?xml version="1.0" encoding="UTF-8"?>

<controllers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.brutosframework.com.br/schema/controllers'
   xsi:schemaLocation='http://www.brutosframework.com.br/schema/controllers http://www.brutosframework.com.br/schema/controllers/brutos-controllers-1.1.xsd'>

    <controller
        class="org.brandao.brutos.helper.controller.SimpleController">

        <bean name="bean"
            target="org.brandao.brutos.helper.controller.SimpleBean">
                <property name="date">
                    <ref bean="bean2" mapping="true"/>
                </property>
        </bean>

        <bean name="bean2"
            target="java.util.Date" factory="factoryDate" method-factory="parse">
                <constructor-arg type="java.lang.String">
                    <value>29/08/1984</value>
                </constructor-arg>
        </bean>

        <bean name="factoryDate"
            target="java.text.SimpleDateFormat">
                <constructor-arg type="java.lang.String">
                    <value>dd/MM/yyyy</value>
                </constructor-arg>
        </bean>

    </controller>

</controllers>
